name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          👋 Hello and welcome!
          Thank you for opening your first issue in this repository. We appreciate your contribution and will review it as soon as possible. If you have any questions or need further clarification, feel free to ask.
          We’re glad to have you here!
        pr-message: |
          👋 Hello and thank you for your first pull request!
          We truly appreciate your contribution to this project. Our team will review your PR shortly. Please make sure you've followed the contribution guidelines and provided clear details about your changes.
          Welcome aboard — we're happy to have you contributing!
